### ISSUE TITLE
Confirming Training Time/Memory Information

### ISSUE THREAD

**Issue by lukemelas** [aimagelab/meshed-memory-transformer#16]
Hello, thank you for your great work! 

I just wanted to confirm some simple information about training time and memory usage, as I didn't see them in the paper/repo, and I wanted to make sure that the code is running correctly on my machine. 

I am running on a single V100 with your parameters: `--batch_size 50 --m 40 --head 8`. I find that this consumes around 6GB of GPU memory and that each epoch takes around 3 hours (so around 30 epochs should take around ~90h = ~4 days). Does this match your training time/memory usage?

I see from the paper that you are training with a (single?) 2080TI, and I see in the code that you stop training dynamically using the `patience` variable. Do you know how many epochs it took for you to stop training on your final run (around 130 CIDEr) and how long this took? 

Thank you again for your work!

**Comment by baraldilorenzo** [comment]
Hi @lukemelas,

many thanks for your interest in this work. Memory consumption and training time depend greatly on whether you are in the XE step or in the RL finetuning step. We were training the model on a single 2080Ti. During XE, a single epoch was taking around 25 minutes (loading features from an SSD), while during RL finetuning it was taking around 3.5-4 hours. Using early stopping, the model was doing around 13 epochs in XE stage and around 20 epochs in RL before reaching the patience. So, at least in our setting, a full training was taking around 3 days.

Do not hesitate to reach us out if you need anything else.

Best,
Lorenzo.

**Comment by lukemelas** [comment]
Hi @baraldilorenzo,

Thank you for your quick and comprehensive response. I really appreciate it! 

I am seeing similar numbers with regard to training time. I will reach out again if I have any more questions (I most likely will), but for now I am closing this issue. 

Thanks again,
Luke
