### ISSUE TITLE
Reg. Training time

### ISSUE THREAD

**Issue by deepak242424** [aimagelab/meshed-memory-transformer#18]
Hi,

Thanks for sharing your code here.

Can you please tell on what type of GPUs you training your model, how much time it took to complete one epoch and the number of epochs till you run your model?

Regards
Deepak Mittal

**Comment by MatteoStefanini** [comment]
Hi @deepak242424 

thanks for your interest in our work!

All the details about GPUs and training times are listed here by @baraldilorenzo :
https://github.com/aimagelab/meshed-memory-transformer/issues/16#issuecomment-617380393

If you have any other doubts don't hesitate to reach us out again.

Best,
Matteo
