### ISSUE TITLE
Is it possible to run this on a new input image?

### ISSUE THREAD

**Issue by SreeHarshaNelaturu** [aimagelab/meshed-memory-transformer#2]
Hello,

Thank you for open-sourcing the code for the awesome projects you've done including M^2 and Show, Control and Tell.

I had read an issue on Show, Control and Tell that it is not possible to use it on new image as the control signals are extracted from COCO/Flickr. Is this the case for this approach as well?

In case one would attempt to scale it for new images (not in coco features) how could one proceed?

Thanks!

**Comment by baraldilorenzo** [comment]
Hi @SreeHarshaNelaturu,

thanks for your interest in our works! 
Currently we only provide detections features for COCO, and we don't provide the code for extracting detection features on new images, so you would have to adjust the code a bit. That shouldn't be difficult in practice: just extract the features using [this repo](https://github.com/peteanderson80/bottom-up-attention/) and pack them in a `.hdf5` file following the format described in our readme. Once you have done this, a small change in the Dataset class should be enough to make it work.

If you want to try, feel free to reach us out if you have any doubts or questions!

Lorenzo.

**Comment by SreeHarshaNelaturu** [comment]
Thank you so much for the response! I will get started on this right away.

I really appreciate the assistance and will get back to you with any
queries.
