### ISSUE TITLE
visualize the attention part like results.png

### ISSUE THREAD

**Issue by jkllbn2563** [aimagelab/meshed-memory-transformer#21]
I really appreciate it that you offer such good work for everyone. I am very interested that how to visualize the image like the results.png in images folder. Thanks a lot !!!!

**Comment by masonwang96** [comment]
Same to me. I would very like to know how to visualize the decoding porcess. Would you kindly share with us? Thanks a lot. @marcellacornia

**Comment by marcellacornia** [comment]
Hi @jkllbn2563  and @masonwang96,
thanks for your interest in our work.
 
For the attention visualizations, we used the Captum library provided by PyTorch for model interpretability and understanding. As mentioned in our paper, we used the Integrated Gradients method following the official documentation: https://captum.ai/docs/extension/integrated_gradients

**Comment by masonwang96** [comment]
Thank a lot. I'll check it out.

**Comment by nilinykh** [comment]
Thank you for specifying the library that you have used for visualisation!
However, is it possible to look at your visualisation script? Would be great if you could share it with us =)
