### ISSUE TITLE
Is this code using the karpathy splits?

### ISSUE THREAD

**Issue by jlxy** [aimagelab/meshed-memory-transformer#26]
Hello. Is this code using karpathy splits? I didn't see any file about the karpathy splits.

**Comment by marcellacornia** [comment]
Hi @jlxy,

Yes, we trained and tested our model on Karpathy splits. You can find caption annotations and train/validation/test splits in the [annotation.zip](https://drive.google.com/file/d/1i8mqKFKhqvBr8kEp3DbIh9-9UNAfKGmE/view?usp=sharing) file reported in the README.
