### ISSUE TITLE
Should mask for padding be used on the attention weights?

### ISSUE THREAD

**Issue by jlxy** [aimagelab/meshed-memory-transformer#27]
Hello! In the decoder part of this code, it seems that mask for padding only be used after each attention module, and in the attention module, only masks for self-attention or cross-attention be used. Should mask for padding be used on the attention weights? In this way, padding information can be prevented from getting into the attended features.

**Comment by baraldilorenzo** [comment]
Hi @jlxy,

the mask for padding in the decoder is built here: https://github.com/aimagelab/meshed-memory-transformer/blob/master/models/transformer/decoders.py#L83
It is then passed to any child attention module, so padding tokens are actually masked.

Best,
Lorenzo
