### ISSUE TITLE
evaluation error

### ISSUE THREAD

**Issue by lixiangpengcs** [aimagelab/meshed-memory-transformer#3]
When I conduct eval script test.py and it report error as:

RuntimeError: Expected object of scalar type Byte but got scalar type Bool for sequence element 1 in sequence argument at position #1 'tensors'

Is there any mistake in evaluation?

**Comment by baraldilorenzo** [comment]
Hi @lixiangpengcs, thanks for downloading our code.
Are you running inside the provided conda environment? The error you are seeing shouldn't appear with the provided packages. If so, please provide me with the full error traceback so that I can run further checks.

Best,
Lorenzo.

**Comment by lixiangpengcs** [comment]
Hi， @baraldilorenzo. Thank you for your reply. I have solved this problem by using your environment. Thanks again for your code.

**Comment by lixiangpengcs** [comment]
I  am confused that when I change pytorch version from 1.1.0 into 1.2.0, It raise this error:
running log:
Meshed-Memory Transformer Evaluation
Evaluation:   0%|                                                                                                                                                                 | 0/500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 77, in <module>
    scores = predict_captions(model, dict_dataloader_test, text_field)
  File "test.py", line 26, in predict_captions
    out, _ = model.beam_search(images, 20, text_field.vocab.stoi['<eos>'], 5, out_size=1)
  File "/home/usrpath/meshed-memory-transformer/models/captioning_model.py", line 70, in beam_search
    return bs.apply(visual, out_size, return_probs, **kwargs)
  File "/home/usrpath/meshed-memory-transformer/models/beam_search/beam_search.py", line 71, in apply
    visual, outputs = self.iter(t, visual, outputs, return_probs, **kwargs)
  File "/home/usrpath/meshed-memory-transformer/models/beam_search/beam_search.py", line 104, in iter
    word_logprob = self.model.step(t, self.selected_words, visual, None, mode='feedback', **kwargs)
  File "/home/usrpath/meshed-memory-transformer/models/transformer/transformer.py", line 50, in step
    return self.decoder(it, self.enc_output, self.mask_enc)
  File "/home/m2releasepython/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/usrpath/meshed-memory-transformer/models/transformer/decoders.py", line 86, in forward
    self.running_mask_self_attention = torch.cat([self.running_mask_self_attention, mask_self_attention], -1)
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for sequence element 1 in sequence argument at position #1 'tensors'
Do you know how to solve this problem?

**Comment by marcellacornia** [comment]
Dear @lixiangpengcs, 
sorry for the delay. 

Our code is compatible with Pytorch 1.1.0, only. If you want to use the newest Pytorch version, you can try by casting to bool the `mask_self_attention` variable. Please let me know if this solves the problem.
