### ISSUE TITLE
about  HDF5 file boxes shape ？

### ISSUE THREAD

**Issue by BetterZH** [aimagelab/meshed-memory-transformer#30]
<HDF5 dataset "544046_boxes": shape (25, 4), type "<f4">
[[  0.         0.       405.69147  342.30185 ]
 [109.02886  216.21622  499.09998  419.3     ]
 [  0.        98.41356  175.93782  311.00922 ]
.......[162.85463  284.66254  215.16975  341.75537 ]]
what does  [a, b, c, d]  mean?

**Comment by beecadox** [comment]
[top, left, bottom, right] corners of bounding boxes.
