### ISSUE TITLE
Architecture related doubt

### ISSUE THREAD

**Issue by shreyanshchordia** [aimagelab/meshed-memory-transformer#36]
Are you feeding the raw image (y * y * 3 dimension) regions or do you feed some deep CNN generated embeddings to your Encoder Decoder network?

**Comment by marcellacornia** [comment]
Hi @shreyanshchordia,

to encode images, we used the features coming from Faster R-CNN trained on Visual Genome (here the source code we used to extract the features: https://github.com/peteanderson80/bottom-up-attention). For each detected region, the model returns a 2048-d feature vector. The input to our encoder is therefore a set of 2048-d feature vectors, each corresponding to a specific region of the image.

Hope this helps!

**Comment by shreyanshchordia** [comment]
Thank you so much for the reply
