### ISSUE TITLE
Meshed decoder for 6 layers Transformer

### ISSUE THREAD

**Issue by HN123-123** [aimagelab/meshed-memory-transformer#38]
I try to use meshed decoder in a 6 layers transfomer model ,but it is in very poor performance. Did you test the meshed  structure in more than 3 layers??

**Comment by marcellacornia** [comment]
Hi @HN123-123,
in our experiments, we noticed a performance drop when using 6 layers. This is the reason why we performed almost all experiments by using 3 layers in both the encoder and the decoder. In the supplementary material ([page 11 of this pdf file](https://arxiv.org/pdf/1912.08226.pdf)), we reported an ablation study using different numbers of encoder and decoder layers.
