### ISSUE TITLE
About the data for COCO online test server

### ISSUE THREAD

**Issue by Cranooooooo** [aimagelab/meshed-memory-transformer#40]
Really brilliant work~
May I ask where can I find the HDF5 data of those 40 775 images for the COCO online test server?
Thanks~

**Comment by marcellacornia** [comment]
Hi @Cranooooooo,
thanks for your interest in our work.

You can find the detection features of the COCO online test set at this [Google Drive link](https://drive.google.com/file/d/1n9Cx6TgaQnx4rP0UoiXUmS75RWDOtJjF/view?usp=sharing).

**Comment by Cranooooooo** [comment]
Truly appreciate ur timely help🙏~

**Comment by HN123-123** [comment]
Are you download the file successfully??? I can not open the file now.
Can you share the file again??  Much thanks for you!!!
