### ISSUE TITLE
About downloading coco_detections.hdf5

### ISSUE THREAD

**Issue by Nobelvictory** [aimagelab/meshed-memory-transformer#66]
Do you have the issue about downloading coco_detections.hdf5? Recently, I met the issue. It showed that too many people were downloading it from the google driver and let me try in 24 hours. And then, I tried it a few times, and all failed. Anyone else knows why?

**Comment by MikeMACintosh** [comment]
it's will help you https://stackoverflow.com/questions/65312867/how-to-download-large-file-from-google-drive-from-terminal-gdown-doesnt-work
