### ISSUE TITLE
The parameters problem of '--features_path & --annotation_folder'

### ISSUE THREAD

**Issue by z972778371** [aimagelab/meshed-memory-transformer#68]
There are six files in the Annotations folder. How to set the '--annotation_folder' parameter? Also  does '--features_path' refer to the coco_detections.hdf5 file
![image](https://user-images.githubusercontent.com/51855588/138074268-007de0fe-6298-42b5-9e85-dd45a9d9a73f.png)

**Comment by Vincent-Ww** [comment]
--annotation_folder should be the path to Annotation folder, rather than path to any specific files.
Yes
