### ISSUE TITLE
The evaluation when runnin test.py

### ISSUE THREAD

**Issue by Timon0327** [aimagelab/meshed-memory-transformer#72]
Hi. When I run the test.py to evaluate, the model just generates <'unk'> without any other tokens.

**Comment by jianqingxie** [comment]
me ,do you solve it?

**Comment by jianqingxie** [comment]
me too, do you solve it?

**Comment by jianqingxie** [comment]
@Timon0327

**Comment by Timon0327** [comment]
> 

Hi, because I had a bug about gather_cuda() from beam_search.py, I modified the data.dtype to float.64 to solve it. When I changed it to original version, the test was normal.
