### ISSUE TITLE
I meet error but i can't solve,please help

### ISSUE THREAD

**Issue by bean-point** [aimagelab/meshed-memory-transformer#8]
PS D:\meshed-memory-transformer-master> python train.py --exp_name m2_transformer --batch_size 50 --m 40 --head 8 --warmup 10000 --features_path meshed_memory_transformer.pth --annotation_folder annotations
Namespace(annotation_folder='annotations', batch_size=50, exp_name='m2_transformer', features_path='meshed_memory_transformer.pth', head=8, logs_folder='tensorboard_logs', m=40, resume_best=False, resume_last=False, warmup=10000, workers=0)
Meshed-Memory Transformer Training
Traceback (most recent call last):
  File "train.py", line 186, in <module>
    cider_train = Cider(PTBTokenizer.tokenize(ref_caps_train))
  File "D:\meshed-memory-transformer-master\evaluation\tokenizer.py", line 48, in tokenize
    p_tokenizer = subprocess.Popen(cmd, cwd=path_to_jar_dirname,stdout=subprocess.PIPE, stderr=open(os.devnull, 'w'))
  File "D:\soft\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "D:\soft\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)

**Comment by marcellacornia** [comment]
Hi @bean-point,
thanks for your interest in our work.

Did you create the conda environment that we provided before running the code?
