### ISSUE TITLE
Test on Custom Dataset 

### ISSUE THREAD

**Issue by Faiail** [aimagelab/meshed-memory-transformer#89]
Is there a possibility to test your model giving images as input? I'm struggling in extracting features, using bottom-up-attention repository.
Thabks

**Comment by marcellacornia** [comment]
Hi @Faiail, thanks for your interest in our work!
To extract features we used [this repository](https://github.com/peteanderson80/bottom-up-attention/). If you want to test our model on images outside the COCO dataset, you need to extract features using the same source code.
