### ISSUE TITLE
Unable to download Coco feature files.

### ISSUE THREAD

**Issue by Akashtyagi08** [aimagelab/meshed-memory-transformer#9]
The download is failing every time. Maybe upload it again or over some other storage location

**Comment by alesolano** [comment]
Can you provide more information, please? I was able to download it last week with no problem.

**Comment by marcellacornia** [comment]
Dear @alesolano and @Akashtyagi08.
thanks for your interest in our work.

The COCO features are stored on Google Drive and I have not found any download problems. 
This is an alternative link for downloading the features: [coco_detections.hdf5](http://ailb-web.ing.unimore.it/releases/show-control-and-tell/coco_detections.hdf5).

Let me know if it works.

**Comment by Akashtyagi08** [comment]
Thanks for the alternative link. I was able to download using it.

**Comment by Jordan-5i** [comment]
hey, I am confused that the coco_detections.hdf5 contains each image region  feature for  train val and test on the “Karpathy” test split?  The global image features in  .hdf5 file?

**Comment by Xiaoming-Zhao** [comment]
> Dear @alesolano and @Akashtyagi08.
> thanks for your interest in our work.
> 
> The COCO features are stored on Google Drive and I have not found any download problems.
> This is an alternative link for downloading the features: [coco_detections.hdf5](http://ailb-web.ing.unimore.it/releases/show-control-and-tell/coco_detections.hdf5).
> 
> Let me know if it works.

Hi, thanks a lot for the alternative link. I think it is more convenient to put this link in the README since the support for Google Drive download with the command line is really poor.
